In [2]:
import numpy as np
np

<module 'numpy' from 'c:\\Users\\milo\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\numpy\\__init__.py'>

Creating arrays

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [9]:
a[2] = 10
a

array([ 1,  2, 10,  4,  5,  6])

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

Multidimentional arrays

In [14]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
n = np.array([[1,2,3], [4,5,6], [7,8,9]])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
n[0,1] = 20
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [23]:
# access and modify rows
n[0] = [1,2,2]
n

array([[1, 2, 2],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
# access columns
n[:,2] = [0,1,2]
n

array([[1, 2, 0],
       [4, 5, 1],
       [7, 8, 2]])

Randomly generated arrays

In [43]:
# rand([rows],[cols])
# ensures that value stays constant
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [44]:
# standard normal distribution
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [45]:
# values above 1
np.random.seed(2)
100*np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [46]:
np.random.seed(2)
np.random.randint(low=0,high=100,size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

Element-wise operaitions

In [48]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [49]:
a + 1

array([1, 2, 3, 4, 5])

In [52]:
b = (10 + (a*2)) ** 2 /100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [53]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

Comparison operations

In [54]:
a

array([0, 1, 2, 3, 4])

In [55]:
a >=2

array([False, False,  True,  True,  True])

In [56]:
a > b

array([False, False,  True,  True,  True])

In [57]:
# return value in array a if condition = true
a[a>b]

array([2, 3, 4])

Summarizing operations

In [58]:
# returns smallest value
a.min()

0

In [59]:
a.max()

4

In [60]:
a.mean()

2.0