Dot Product

In [4]:
import numpy as np

In [22]:
U = np.array([[2,4,5,6], [1,2,1,2], [3,1,2,1]])
V = np.array([[1,1,2], [0,0.5,1], [0,2,1], [2,1,0]])

u = np.array([2,4,5,6])
v = np.array([1,0,0,2])

In [6]:
def vectorMultiplication(u,v):
    assert u.shape[0] == v.shape[0]
    result = 0.0
    for i in range(u.shape[0]):
        result = result + u[i] * v[i]
    
    return result

In [7]:
vectorMultiplication(u,v)

14.0

In [9]:
u.dot(v)

14

Matrix - Vector Multiplication

In [15]:
def matVecMultiplication(U,v):
    assert U.shape[1] == v.shape[0]
    numRows = U.shape[0]
    result = np.zeros(numRows)

    for i in range(numRows):
        result[i] = vectorMultiplication(U[i],v)
    
    return result

In [16]:
matVecMultiplication(U,v)

array([14.,  5.,  5.])

In [17]:
U.dot(v)

array([14,  5,  5])

Matrix - Matrix Multiplication

In [18]:
def matMatMultiplication(U,V):
    assert U.shape[1] == V.shape[0]

    numRows = U.shape[0]
    numCols = V.shape[1]

    result = np.zeros((numRows, numCols))

    for i in range(numCols):
        vi = V[:,i]
        Uvi = matVecMultiplication(U,vi)
        result[:,i] = Uvi
    
    return result

In [23]:
matMatMultiplication(U,V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [24]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

Identity Matrix

In [29]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

Inverse Matrix

In [32]:
vs = V[[0,1,2]]
vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [33]:
vsInv = np.linalg.inv(vs)
vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [34]:
vsInv.dot(vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])